package com.st.ui.theme

const val TITLE_MAX_LINES = 1
const val SUBTITLE_MAX_LINES = 1
const val DESCRIPTION_MAX_LINES = 4
const val CAPTION_MAX_LINES = 4
const val BTN_MAX_LINES = 1
const val AVAILABLE_DEMOS_MAX_LINES = 3
const val POPUP_IN_TRANSITION_DURATION = 100
const val POPUP_OUT_TRANSITION_DURATION = 300
const val POPUP_DEFAULT_TIMEOUT = 2500L
